apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      volumes:
      - name: proxy-config
        configMap:
          name: proxy-configmap
          defaultMode: 0755
      containers:
      - name: squid
        image: syakesaba/docker-sslbump-proxy:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: proxy-config
           mountPath: /usr/local/bin
        command:
         - /usr/local/bin/icap
