apiVersion: v1
kind: Pod
metadata:
  name: artillery
  labels:
    env: test
spec:
  containers:
  - name: artillery
    image: peltops/gws_artillery:v2
    command: ["/bin/sh"]
    args: ["-c", "export http_proxy=http://172.18.0.5:3128; export https_proxy=http://172.18.0.5:3128; artillery run /conf.yml"]